---
- name: deploy netplan
  hosts: servers
  become: yes
  tasks:
    - name: use netplan.j2
      template:
        src: ../templates/netplan.j2
        dest: /etc/netplan/99-custom-config.yaml
        owner: root
        group: root
        mode: '0600'
      notify: apply
  handlers:
    - name: apply
      command: netplan apply
...
